name: Build Website
run-name: Build Website

on:
    push:

jobs:
    build:
        name: Build NPM Project
        runs-on: ubuntu-latest
        container: node
        steps:
            - name: Clone Repository
              uses: ztimson/actions/clone@develop

            - name: Install Dependencies
              run: npm i

            - name: Build Project
              run: npm run build

            - name: Upload Artifacts
              if: ${{inputs.artifacts}} != "false"
              uses: actions/upload-artifact@v3
              with:
                  name: website
                  path: dist
                  retention-days: 7
    tag:
        name: Tag Version
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repository
              uses: ztimson/actions/clone@develop

            - name: Tag Version
              uses: ztimson/actions/tag@develop

    publish:
        name: Build & Push Dockerfile
        needs: build
        uses: ztimson/actions/.github/workflows/docker.yaml@develop
        with:
            dockerfile: website/Dockerfile
            name: phone-reminders/website
            repository: ${{github.server_url}}/${{github.repository}}.git
            pass: ${{secrets.DEPLOY_TOKEN}}
